---
grails:
    profile: web
    codegen:
        defaultPackage: test.g323.consul
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    # spring cloud consul integration settings
    #
    # By default, taken from the Environment:
    #  - service name is ${spring.application.name}
    #  - instance id is the Spring Context ID, which by default is
    #    ${spring.application.name}:comma,separated,profiles:${server.port}
    #  - port is ${server.port}
    #
    application:
        name: test-g323-consul
    cloud:
        consul:
#            host: localhost
#            port: 8500
#            discovery:
#                health-check-path: /health
#                healthCheckInterval: 5s
            ## To enable consul distributed configuration:
            ## We can create the property by going to the “KEY/VALUE” section,
            ## then entering “/config/test-g323-consul/my/prop” in the “Create Key” form
            ## and “Hello Consul” as value. Then click the “Create” button to save.
            config:
                enabled: true

# Spring Actuator Endpoints should be enabled for consul health check
endpoints:
    enabled: true
    jmx:
        enabled: true
        unique-names: true
    beans:
        sensitive: false
    autoconfig:
        sensitive: false
    actuator:
        sensitive: false
    configprops:
        sensitive: false
    dump:
        sensitive: false
    mappings:
        sensitive: false
    logfile:
        sensitive: false
    consul:
        sensitive: false   # default is false

server:
    port: 8090

---
grails:
    cors:
        enabled: true
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none


---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
